# Generated by Django 3.1.1 on 2021-08-30 19:53

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='cart',
            managers=[
                ('manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
