# Generated by Django 3.1.1 on 2021-09-17 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0003_auto_20210916_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='products',
            field=models.ManyToManyField(blank=True, to='carts.SaleProduct'),
        ),
    ]
