# Generated by Django 3.1.1 on 2021-09-28 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Search',
        ),
    ]
